### ISSUE TITLE
Bank.bank().withdraw()

### ISSUE THREAD

**Issue by Ayylmao42000** [rs-peer/rsp3#51]
Bank.bank().withdraw(item -> item.getName().startsWith("Stamina potion"), 1) fails
Bank.bank().withdraw(item -> item.getName().startsWith("Stamina potion"), ANY AMOUNT > 1) withdraws
seems to not like amount 1 for some reason, > 1 and it withdraws items successfully

**Comment by d-o-g** [comment]
Bank.bank() is not the correct way to access it btw, it should be Inventory.bank()
and you should store the variable i.e
```
Bank bank = Inventory.bank()
bank.withdraw(...)
bank.withdraw(...)
...
```
