### ISSUE TITLE
Inverted Game.getClient().setSceneRenderingEnabled

### ISSUE THREAD

**Issue by MzScorpio** [rs-peer/rsp3#7]
Interface method:
https://github.com/rs-peer/rsp3/blob/bc3ce7204ea0f801d69cb57fe89d2c191f3657bf/api/src/main/java/jag/game/RSClient.java#L32

The actual value passed has to be `!enabled` as done here
https://github.com/rs-peer/rsp3/blob/bc3ce7204ea0f801d69cb57fe89d2c191f3657bf/ui/src/main/java/org/rspeer/ui/component/menu/BotMenuBar.java#L49

**Comment by Lezor91** [comment]
Addressed.
